### ISSUE TITLE
Create a 'dope' button on rant

### ISSUE THREAD

**Issue by telamon** [decentlabs-north/rant#23]
When clicked:
```js
await pubKernel.bump(rantId)
```

**Comment by ogooluwanick** [comment]
Please assign to me friend... Can create dope btn that will match color shemes of webapp.

**Comment by telamon** [comment]
@ogooluwanick no assignment needed =) just fork off and PR.
We're on discord if you wanna know more https://discord.gg/8RMRUPZ9RS 👊

**Comment by ogooluwanick** [comment]
Ok will do.

**Comment by telamon** [comment]
![image](https://user-images.githubusercontent.com/148454/199979127-dd96708b-fde8-4da3-a2b3-6820074d179d.png)

@ogooluwanick so on linux/chromium without an emoji system-font installed the button is just blank :'/

But we're also trying to build an app using only CSS and HTML; Maybe there's a :hankey:-svg that can be stored in CSS:background-image. I don't know..

 if you wanna try and improve it then that would be very cool! =)

**Comment by ogooluwanick** [comment]
Yes friend I understand I've got the svg already but I cant find the btn on the website, can I get a link to it. @telamon
